### ISSUE TITLE
Use @media for json-encode mixin

### ISSUE THREAD

**Issue by jamiebuilds** [KittyGiraudel/SassyJSON#30]
I'm not sure about previous discussion on this topic. However the current way of storing json doesn't seem all that safe if it were needed on an actual website.

This is how sass's debug info works:

``` css
@media -sass-debug-info {
  filename {
    font-family: file\:\/\/\/Users\/thejameskyle\/git\/thejameskyle\/bootcamp\/node_modules\/sassyjson\/src\/encode\/mixins\/_json\.scss;
  }

  line {
    font-family: \000037;
  }
}
```

I'm proposing making the json encode mixin work the same way:

``` css
@media -json-encode {
  json {
    font-family: "[1, 2, 3]";
  }
}
```

This would prevent any possible collision of actual styles.
