### ISSUE TITLE
Export map to json file.

### ISSUE THREAD

**Issue by ezekg** [KittyGiraudel/SassyJSON#74]
Ran into a use case for this. I needed to get a list of selectors that use a certain mixin from a Sass file for use in a PHP class (via parsing a JSON map to an associative array). So, came up with a somewhat hacky solution, as I don't know Ruby much at all. 

Ruby

``` ruby
# -------------------------------------------------------------------------------------------------------
# SassyJSON : write json file from passed Sass map to path/to/filename
# -------------------------------------------------------------------------------------------------------
# @param $path [string] : directory path to write $string
# @param $filename [string] : file name to write to $path
# @param $string [string] : json to write to $filename
# -------------------------------------------------------------------------------------------------------

module Sass::Script::Functions
    def SassyJSON_export(path, filename, string)
        # define root path up to current folder
        root = File.dirname(options[:filename] || ".")
        # open file [create new file if file does not exist], write $string to $root/$path/$filename
        File.open("#{root}/#{path}/#{filename}.json", "w") { |f| f.write(string) }
        # return string for use in css
        return string
    end
end
```

Sass

``` scss
// ./sass/style.scss

@mixin json_export($path, $filename, $map) {
    @at-root {
        %json_export {
            content: "#{SassyJSON_export(unquote($path), unquote($filename), unquote(json_encode($map)))}";
        }
    }
}

$map: (
    hello: world,
);

@include json_export("../json", "config", $map);
```

New JSON file in `./json/config.json`

``` json
{"hello": "world"}
```

The `json_export()` mixin takes a directory `$path`, `$filename`, and a Sass `$map` as arguments, then it converts the `$map` to a JSON map with the `json_encode()` function, then Ruby creates a new file, and writes the contents of the json string to it. I'm sure all of these functions could be improved, but it is still a nice proof of concept.

Might as well, right?
